name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  tests:
    name: Run tests & Scan
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Composer install
        uses: php-actions/composer@v6

      - name: Generate Laravel key
        run: cp .env.example .env && ./artisan key:generate

      - name: PHPunit
        uses: php-actions/phpunit@v3
        with:
          php_extensions: xdebug
          configuration: phpunit.xml
          log_junit: reports/junit.xml
          args: --coverage-clover reports/coverage.clover.xml

      - name: Fix report paths
        run: |
          sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' reports/coverage.clover.xml
          sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' reports/junit.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.php.tests.reportPath=reports/junit.xml
            -Dsonar.php.coverage.reportPaths=reports/coverage.clover.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
