name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  tests:
    name: Run tests & Scan
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: php-actions/composer@v6

      - name: Generate Laravel key
        run: cp .env.example .env && ./artisan key:generate

      - uses: php-actions/phpunit@v3
        with:
          configuration: phpunit.xml
          log_junit: storage/phpunit/junit.xml
          args: --coverage-clover storage/phpunit/coverage.clover.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.php.tests.reportPath=./storage/phpunit/junit.xml
            -Dsonar.php.coverage.reportPaths=./storage/phpunit/coverage.clover.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
